name: notebook-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert nbformat
          pip install -r requirements.txt || true
      - name: Execute notebooks
        run: |
          python scripts/run_notebooks.py
